spring:
  application:
    name: entable-be
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
server:
  port: 8082

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  expiration:
    duration:
      minutes: 25

logging:
  level:
    org:
      example:
        entablebe*: debug

cypher:
  encryption:
    key: ${CYPHER_ENCRYPTION_KEY}

base:
  path: ${BASE_PATH}
