spring:
  servlet:
    multipart:
      max-file-size: 10MB
  application:
    name: entable-be
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: 1321
    password: 1233
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  batch:
    job:
      enabled: false
    size: 100
    jdbc:
      initialize-schema: always
server:
  port: 8082

jwt:
  secret:
    key: qE0lktO7x3ldlBV/FZwl/wXOHPfGxk4v4P8Fo/SAHGkuDYJN21FEqFmpGfg5+oRJ7X/OWmRbT4x9/jEMBLMVRjM0EHrorSWKmVtD4BHrsSn0jQjVRP39JrQUNuGWXvRBBOvpG5isMhQqWvSjfdweWjID+owGqCL5ygPiZp6MR8IJRVviHWwRcxvz7xGZrdPekLlBLU94nFKUIuK/Ab5M2FnjpdJlNHPvwr8OCtelyx1G8mt/deQ8gpidU/bF65QE3Jdg3xHTL8SB3WQFKrKcQg+roUams5Sj/bACsr+VYkT3nCFwwY+axNaWn6C1kxLfz3572Ygag0Ij+UfN538oYV7KCfR5pOM3sE/3RTzuzQQ=
  expiration:
    duration:
      minutes: 25

logging:
  level:
    com:
#      zaxxer:
#        hikari: TRACE
    org:
      example:
        entablebe*: debug
      springframework.transaction.interceptor*: TRACE
cypher:
  encryption:
    key: L2r01kJ/q5foSD1EbjvTi+vP3570cBp9HPc45LNbvHu2skgHzZ8fcqriJLgZH22D

base:
  path: 1231

resilience4j:
  ratelimiter:
    configs:
      default:
        limitForPeriod: 10
        limitRefreshPeriod: 5s
        timeoutDuration: 100ms