spring:
  servlet:
    multipart:
      max-file-size: 10MB
  application:
    name: entable-be
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  batch:
    job:
      enabled: false
    size: 100
server:
  port: 8082

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  expiration:
    duration:
      minutes: 120

logging:
  level:
    org:
      example:
        entablebe*: debug
      springframework.transaction.interceptor*: TRACE

cypher:
  encryption:
    key: ${CYPHER_ENCRYPTION_KEY}

base:
  path: ${BASE_PATH}

resilience4j:
  ratelimiter:
    configs:
      default:
        limitForPeriod: 10
        limitRefreshPeriod: 5s
        timeoutDuration: 100ms